version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/docker/cypress"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/docker/php"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/docker/node"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/docker/nginx"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
