version: "3.4"

services:
  api:
    build: php
    working_dir: /app/api
    environment:
      - HOME=/tmp
    user: "${UID}:${GID}"
    volumes:
      - ../api:/app/api
    tmpfs:
      - /tmp
    depends_on:
      - mariadb

  app:
    image: node:14-alpine
    working_dir: /app/app
    environment:
      - HOME=/tmp
    command: yarn serve
    user: "${UID}:${GID}"
    volumes:
      - ../app:/app/app
    tmpfs:
      - /tmp

  nginx:
    build: nginx
    ports:
      - "8180:80"
    volumes:
      - ../:/app:ro
    tmpfs:
      - /tmp
    depends_on:
      - api
      - app

  mariadb:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    tmpfs:
      - /tmp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=
    ports:
      - "8190:80"
    tmpfs:
      - /tmp
    depends_on:
      - mariadb
