# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    geoip.database: '/usr/share/GeoIP/GeoLite2-Country.mmdb'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php,Request}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\EventSubscriber\RateLimitSubscriber:
        bind:
            $delay: '%app.post.delay%'
            $count: '%app.post.max_count%'

    MaxMind\Db\Reader:
        arguments:
            - '%geoip.database%'

    geertw\IpAnonymizer\IpAnonymizer:

    App\ParamConverter\StatisticsRangeParamConverter:
        bind:
            $rangeMonths: '%app.range_months%'

    Nelmio\ApiDocBundle\Controller\DocumentationController: '@nelmio_api_doc.controller.swagger'

    App\Cache\ApiDocCacheWarmer:
        tags:
            - { name: kernel.cache_warmer, priority: -1 }
