# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    geoip.database: '/usr/share/GeoIP/GeoLite2-Country.mmdb'
    env(EXPECTED_PACKAGES): '["pkgstats","pacman"]'
    validator.expected_packages: '%env(json:EXPECTED_PACKAGES)%'
    validator.max_missing: 0.2

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $environment: '%kernel.environment%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Request/'
            - '../src/DataFixtures/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    MaxMind\Db\Reader:
        arguments:
            - '%geoip.database%'

    Nelmio\ApiDocBundle\Controller\DocumentationController: '@nelmio_api_doc.controller.swagger'

    # Workaround for https://github.com/nelmio/NelmioApiDocBundle/issues/1874
    nelmio_api_doc.render_docs.html.asset:
        synthetic: true

    App\Cache\ApiDocCacheWarmer:
        tags:
            - { name: kernel.cache_warmer, priority: -1 }

    App\Validator\ContainsPackagesValidator:
        bind:
            $expectedPackages: '%validator.expected_packages%'
            $maxMissing: '%validator.max_missing%'

when@dev:
    services:
        _defaults:
            autowire: true
            autoconfigure: true
            bind:
                $environment: '%kernel.environment%'

        App\DataFixtures\:
            resource: '../src/DataFixtures/'

        League\ISO3166\ISO3166:

when@test:
    services:
        _defaults:
            autowire: true
            autoconfigure: true
            bind:
                $environment: '%kernel.environment%'

        App\DataFixtures\:
            resource: '../src/DataFixtures/'

        League\ISO3166\ISO3166:
