name: update

on:
  schedule:
    - cron: '0 2 */1 * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Install Just
        uses: extractions/setup-just@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.MAINTENANCE_TOKEN }}
      - name: Pulling Docker images
        run: just compose pull
      - name: Pulling Cypress Docker image
        run: just compose -f docker/cypress-open.yml pull
      - name: Building Docker images
        run: just compose build
      - name: Maintain Composer cache
        uses: actions/cache@v4
        with:
          path: api/.cache/composer
          key: composer-${{ hashFiles('api/composer.lock') }}
          restore-keys: composer-
      - name: Maintain pnpm cache
        uses: actions/cache@v4
        with:
          path: app/.cache/node
          key: pnpm-${{ hashFiles('app/pnpm-lock.yaml') }}
          restore-keys: pnpm-
      - name: Install dependencies
        run: just install
      - name: Update dependencies
        run: just update
      - name: Run Rector
        run: just rector
      - name: Fix code style
        run: just fix-code-style
      - run: just test
      - run: just test-db
      - run: just test-e2e
      - name: Commit updates
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Update dependencies
          commit_user_name: Maintenance Bob
          commit_user_email: bob@archlinux.de
          commit_author: Maintenance Bob <bob@archlinux.de>
